### ISSUE TITLE
what is `mask` doing?

### ISSUE THREAD

**Issue by taxio** [tech-srl/code2vec#10]
Hi, @urialon 

I have a question about the code of building model.
What is `mask` doing?
https://github.com/tech-srl/code2vec/blob/master/model.py#L309-L311
I can predict that this code is related to updating parameters of `attention weight`, but I could not read how it corresponds to the formula of the paper.

Thank you.

**Comment by urialon** [comment]
Hi,
Every prediction has up to `max_contexts` contexts (=tuples of paths and their tokens), which is set to `200` [by default](https://github.com/tech-srl/code2vec/blob/master/common.py#L18).
However, most methods have *less* than `200` contexts. So we pad these examples with dummy contexts such that all examples will have the same shape and we can batch all examples together.

So, the model computes attention scores for each of these 200 contexts. But not all of them are "real", some of them are just paddings. So before computing the softmax, we add the value `minus infinity` to the scores that were computed for these padded contexts, such that after softmax-ing - their attention weights would be zero and these paddings will not get any attention (softmax squashes minus infinity to zero).

Let me know if you have any more questions,
Best,
Uri

**Comment by taxio** [comment]
I got it!!
Thank you very much ❤️
