### ISSUE TITLE
Target Labels Dictionary Location

### ISSUE THREAD

**Issue by NURx2** [tech-srl/code2vec#111]
Hi,

Thank you for this amazing project!

Is there any dictionary from where model creates target classes? I need it to check if model considers all target classes correctly. Found `target_to_count` variable https://github.com/tech-srl/code2vec/blob/37dc998c3b427594241165339b2200fcfdff2596/preprocess.py#L127 which looks like something similar, but it doesn't contain all method names the model was trained on.

Thank you.

**Comment by urialon** [comment]
Hi @NURx2 ,
Thank you for your interest in this project and for your kinds words!

Yes, during preprocessing the `preprocess.py` script creates a dictionary from all target labels that were seen in the training data.
Note the `max_size=int(args.target_vocab_size)` argument, which limits the dictionary size. So only the top-`max_size` labels are kept, and more rare labels are ignored.

Of course, you can increase this value using the `target_vocab_size` flag.

By the way, our [https://code2seq.org/](https://code2seq.org/) project is newer and stronger than this project.

Best,
Uri

**Comment by NURx2** [comment]
Dear @urialon,

Yes, the problem was in the small `target_vocab_size` value. Thank you for the quick response.

Currently, I noticed that `target_to_count` contains the file names not the method names. Is it a correct behavior? Should I specify targets for each code snippet in a file name?

Thanks,
Ainur

**Comment by NURx2** [comment]
> Currently, I noticed that `target_to_count` contains the file names not the method names. Is it a correct behavior? Should I specify targets for each code snippet in a file name?

Figured out the last issue. I use [astminer](https://github.com/JetBrains-Research/astminer) to generate input path contexts and it saves them like the pair of the filename and the triples of path contexts.

**Comment by urialon** [comment]
Great, glad to hear :)
