### ISSUE TITLE
java-small processing, extract.py argument error

### ISSUE THREAD

**Issue by arghavanmo** [tech-srl/code2vec#114]
Hi,
I am trying to process java-small raw data (.java files). I received the below error after updating the directories in the preprocess.sh file. Here is a snapshot of the error:
<img width="440" alt="code2vec_error" src="https://user-images.githubusercontent.com/12644790/114197897-cf3fcc00-9920-11eb-98ae-72b14b66fadd.png">

Would you please help me to solve this issue?

**Comment by urialon** [comment]
Hi,
Please provide your `preprocess.sh` file, and the `git diff` output.

Best,
Uri

**Comment by arghavanmo** [comment]
Hi,
Here is the diff content:

`$ git diff preprocess_main.sh preprocess.sh
diff --git a/preprocess.sh b/preprocess.sh
index e04fa94..e543237 100644
--- a/preprocess.sh
+++ b/preprocess.sh
@@ -18,16 +18,16 @@
 #   recommended to use a multi-core machine for the preprocessing
 #   step and set this value to the number of cores.
 # PYTHON - python3 interpreter alias.
-TRAIN_DIR=my_train_dir
-VAL_DIR=my_val_dir
-TEST_DIR=my_test_dir
+TRAIN_DIR= java-small/training
+VAL_DIR= java-small/validation
+TEST_DIR= java-small/est
 DATASET_NAME=my_dataset
 MAX_CONTEXTS=200
 WORD_VOCAB_SIZE=1301136
 PATH_VOCAB_SIZE=911417
 TARGET_VOCAB_SIZE=261245
 NUM_THREADS=64
-PYTHON=python3
+PYTHON=python
`
[preprocess.txt](https://github.com/tech-srl/code2vec/files/6297143/preprocess.txt)
btw: I change .sh tp .txt to be able to upload the file here.

**Comment by arghavanmo** [comment]
Hi, 
I am going to close this issue. I received this error while I was working on windows 10. Still, i don't know what was the reason and I was not able to solve it. But, I switch to linux and everything is fine now.

**Comment by arghavanmo** [comment]
Hi,
I am going to close this issue. I received this error while I was working on windows 10. Still, i don't know what was the reason and I was not able to solve it. But, I switch to linux and everything is fine now.

**Comment by urialon** [comment]
Hi @arghavanmo ,
Sorry for not responding, I missed your last message.
I'm glad that everything is solved, switching from windows to linux usually helps :-)

Uri
