### ISSUE TITLE
Can we cluster code vector representation to detect similar code?

### ISSUE THREAD

**Issue by ArnolFokam** [tech-srl/code2vec#120]
Hello, Thanks again for this incredible work. I think my question is self-explanatory but in case you need further details. I am wondering if I can use an unsupervised learning method to cluster code clones together. 

Having read your presentation and sifting through your repo, I think as long as I am able to get the vector representation of a particular source code. I can do pretty anything with it regarding numerical stuffs (correct me if I'm wrong)

So, my hypothesis is that I can get the vector representation of source codes and cluster them into group of similar vectors using the euclidean distance between these vectors. So I have the following questions regarding this:

- Is it feasible in a general point of view ?
- Can code2vec permits me to achieve this ?
- If the answer to the previous question is affirmative, can I use known clustering methods to do so (kMeans, kNN's etc)
- If not, what approach can I use concerning code2vec (considering the fact that I may not have labelled data)

Thanks for reading through.

**Comment by urialon** [comment]
Hi @ArnolFokam ,
Thank you for your kind words and for your interest in code2vec!

Yes, this is generally possible, both technically and conceptually! (all my answers are "yes" :-))
See: https://github.com/tech-srl/code2vec#exporting-the-code-vectors-for-the-given-code-examples

Best,
Uri

**Comment by ArnolFokam** [comment]
Wonderful !!!

I will give it a try and give you updates. For now, I will close this issue.
