### ISSUE TITLE
Model for other prediction task

### ISSUE THREAD

**Issue by anon721702** [tech-srl/code2vec#121]
I want to use this model for predicting something different than the method name using code2Vec.  How/Where should I modify the implementation for the same. What other things need to be considered in this scenario.

**Comment by urialon** [comment]
Hi @anon721702 ,
Thank you for your interest in code2vec.

It generally depends on the task, but in many cases, you can just create a different training data with the same format.
In this case, you don't need to change the implementation of the network itself (only the data extraction code).

Best,
Uri

**Comment by anon721702** [comment]
Thanks for the response, sir. I am not able to visualize java14m.dict.c2v file as it has some weird symbol that couldn't get converted into readable format. The remaining datasets (test, training, and validation) are visible to me in text format. 
Can you please share dict file in text format.

**Comment by urialon** [comment]
Right, this is a binary serialized file.

You can see in the code how this file is used, and open it in the same way:

https://github.com/tech-srl/code2vec/blob/master/vocabularies.py#L224
