### ISSUE TITLE
Training code2vec error

### ISSUE THREAD

**Issue by binglinchengxiash** [tech-srl/code2vec#124]
File "code2vec/code2vec/path_context_reader.py", line 190, in _map_raw_dataset_row_to_input_tensors
    split_contexts = tf.compat.v1.string_split(contexts_str, sep=',', skip_empty=False)
TypeError: string_split() got an unexpected keyword argument 'sep

**Comment by urialon** [comment]
Hi,
Thank you for your interest in code2vec!

Which Tensorflow version are you using?
Can you try using the Tensorflow backend with Tensorflow 1.x?

**Comment by binglinchengxiash** [comment]
tf2.0
