### ISSUE TITLE
Missing dict.c2v file during training of a model on Python

### ISSUE THREAD

**Issue by Avra2** [tech-srl/code2vec#137]
Hello,

I run `train.sh` on dataset where I only have `train.c2v` and `test.c2v` in `data` folder as those are the only output I got from astminer tool on Python files.

![image](https://user-images.githubusercontent.com/45768058/140595138-59ba7d4a-34c8-45f7-920e-c2999ffacbec.png)

Below is output I got from astminer tool:

![image](https://user-images.githubusercontent.com/45768058/140595126-eb58fb7a-6139-4a7b-b3ee-5adcef08387a.png)

Can you please just post a sample `dict.c2v` code that we can run on `train.c2v` file as I guess your `dict.c2v` is information is extracted from `train.c2v` content?

I see what you dump to this file are:

```
        pickle.dump(word_to_count, file)
        pickle.dump(path_to_count, file)
        pickle.dump(target_to_count, file)
        pickle.dump(num_training_examples, file)
```

Given the output of astminer we have is > 6GB, so I am not sure how to fill it manually as data is very large, so can you please guide us on that?

**Comment by Avra2** [comment]
> Hello,
> 
> I run `train.sh` on dataset where I only have `train.c2v` and `test.c2v` in `data` folder as those are the only output I got from astminer tool on Python files.
> 
> ![image](https://user-images.githubusercontent.com/45768058/140595138-59ba7d4a-34c8-45f7-920e-c2999ffacbec.png)
> 
> Below is output I got from astminer tool:
> 
> ![image](https://user-images.githubusercontent.com/45768058/140595126-eb58fb7a-6139-4a7b-b3ee-5adcef08387a.png)

**Comment by urialon** [comment]
Hi @Avra2 ,
I think it would be easiest if you run the standard pipeline, with our extractor (not astminer), on a directory containing a single small *.java file, and examine the results?

**Comment by Avra2** [comment]
@urialon. Thank you. Your extractor on code2vec public project is for Java not for Python as I see it. Can you please guide us how to extract Python AST paths with your extractor?

**Comment by urialon** [comment]
The provided extractor in this repository is for Java, not python.
I suggested that you preprocess a tiny java example, to examine the Java outputs to see the format of the data and the dictionary files that it produces, and this way will be able to adapt your python pipeline.

Alternatively, you can switch to [code2seq](https://code2seq.org/) which has better encoder and decoder, and also a python extractor:
https://github.com/tech-srl/code2seq/tree/master/Python150kExtractor

Best,
Uri

**Comment by Avra2** [comment]
@urialon. Thank you. Yes. I will try code2seq.
