### ISSUE TITLE
JavaExtractor: Incorrect path length calculation

### ISSUE THREAD

**Issue by clause** [tech-srl/code2vec#14]
In FeatureExtractor, the length of a path is calculated as `int pathLength = sourceStack.size() + targetStack.size() - 2 * commonPrefix;` (line 140).  I believe this is calculation is one more than the actual path length as it is counting the commonNode twice.  

I suggest calculating the length as `currentSourceAncestorIndex + currentTargetAncestorIndex + 1`

**Comment by urialon** [comment]
Hi James,
First, thanks! But it is actually counting edges and not nodes. I.e., the length of the path is defined there as the number of edges. Of course, the length could have been defined as the number of nodes (which is edges+1), but at the time I thought that counting edges makes more sense....
Additionally, the commonNode is *decreased* from the path length twice, so the result is the number of nodes in the path, excluding the common node, which equals to the number of edges.

I know it's a little confusing, I just ran it in debug mode and verified. 
Your suggestion makes the length even smaller by 1.
I agree that maybe it could have made more sense to define the length as the number of nodes in the first place.

**Comment by clause** [comment]
Thanks for clearing that up.  So the smallest path length is 2 as paths will always have at least three nodes: (source, parent+, target)?

**Comment by urialon** [comment]
Yes, exactly.
