### ISSUE TITLE
How to use the Mode I trained ?

### ISSUE THREAD

**Issue by IHaveNoEnglishName** [tech-srl/code2vec#140]
Hello, I am very Interested in you code2word! 
I have make a model on code2vec in python, and successfully get the model, the path saved like this:
![image](https://user-images.githubusercontent.com/28301313/145765225-4134496c-41a0-4635-9a2d-17cd550ba72b.png)

but I don`t know to use this model, as your example command is:
```
python3 code2vec.py --load models/java14_model/saved_model_iter8.release --test data/java14m/java14m.test.c2v
```
but my model look likes have many file, I don't know which one is the model to use, or  I just use the path as the pragram of 
the `--load` option? like this :
```
python3 code2vec.py --load models/python150 --test data/python150/python150.test.c2v
```

**Comment by urialon** [comment]
Hi @IHaveNoEnglishName ,
Thank you for your interest in code2vec!

Use the prefix: `--load --load models/python150/saved_model_iter14`

Best,
Uri

**Comment by IHaveNoEnglishName** [comment]
Thany you, the model worked!
