### ISSUE TITLE
Question About Exporting the code vectors for the given code examples

### ISSUE THREAD

**Issue by brcsnt** [tech-srl/code2vec#143]
Hello, I am getting the file not found error in the _preprocess.sh_ code. Do you have any directions? The file path I specified is the java files in the java-small folder. I will be grateful if you could help me, thanks.

![image](https://user-images.githubusercontent.com/42771566/148757707-58d65f66-3c63-4a68-a8f4-4e75c5991e9b.png)

**Comment by brcsnt** [comment]
Hello again, I was able to download and run the trained model by looking at the Read me file. The following codes were able to generate targets and tokens txt files. I'm trying to create code2vec for the code in the input java file I have. I'm using this code but it's getting an error somewhere, can you guide me? 

Also, when some of the code runs, Input.java.vectors is created on the left, but the file is empty. In addition, 6 is written in the Input.java.num_examples file. Thank you very much for your help.

!python3 code2vec.py --load models/java14_model/saved_model_iter8.release --export_code_vectors --test Input.java

![image](https://user-images.githubusercontent.com/42771566/148931777-9fb6b0c0-e2ac-45f0-892c-5dea795420c5.png)


Error:

![image](https://user-images.githubusercontent.com/42771566/148932386-f1a6e7d0-1d10-4a0d-a674-974e7c5e221a.png)

**Comment by urialon** [comment]
Hi @brcsnt ,

Did you try running the commands exactly as they are in the README file?
What exactly are you trying to do?

Best,
Uri

**Comment by brcsnt** [comment]
Hello, 
when I tried the following code, I was able to obtain the vectors for the code in the given java input file. But I simply wanted to do this. I wanted to get code vectors for all java files in a given path. I was able to do that with this code. 

Thanks,

`!python3 code2vec.py --load models/java14_model/saved_model_iter8.release --predict --export_code_vectors `

**Comment by urialon** [comment]
Hi @brcsnt , 
You asked a question and then closed this issue. Do you have any questions?

**Comment by brcsnt** [comment]
Hello, 
I had a question but then I was able to solve it.  I don't have any questions right now. That's why I closed the issue. 
Thanks again.
