### ISSUE TITLE
I need help with decompose step. 

### ISSUE THREAD

**Issue by ma0889** [tech-srl/code2vec#146]
Hello, 
Thank you for sharing your project with us!! I'm interested in the Code2vec project and I read your paper and I watched the youtube presentation.  
I have a concern about the Code2vev project. I'm sorry if my questions are so naive. 
I have an OpenMP dataset that is written in C I need to convert the code into AST and decompose it to get the vectors.
I mean I need to do the first part of the Code2vev project( I have to stop before the aggregating step ) 

Is there any way to apply code2vec on the OpenMP dataset? 
How can I use the first part of the code2vec project?

**Comment by ma0889** [comment]
Hi @urialon 

Thank you for your response!

**Comment by urialon** [comment]
Hi @ma0889 ,
We just released a model that performs better than OpenAI's Codex for C.

https://arxiv.org/pdf/2202.13169.pdf
https://github.com/VHellendoorn/Code-LMs

Best,
Uri
