### ISSUE TITLE
Using one example

### ISSUE THREAD

**Issue by colebuckleyy** [tech-srl/code2vec#150]
If I train a code2vec model on a dataset, and I want to just embed one source code file into a vector, is there any way I can do that after the code2vec model has been trained/saved.

**Comment by urialon** [comment]
Hi @colebuckleyy ,
Thank you for your interest in our work, and sorry for the delayed response.
Did you see https://github.com/tech-srl/code2vec#exporting-the-code-vectors-for-the-given-code-examples ?

Uri
