### ISSUE TITLE
Path Embedding Problem

### ISSUE THREAD

**Issue by yilinfang** [tech-srl/code2vec#153]
Thank you for the awesome work！Here comes a problem, how can I get the vectors emmbed from the Paths in the AST of the source code?

**Comment by urialon** [comment]
Hi @yilinfang ,
Thank you for your interest in our work!

Have you seen this part of the README? https://github.com/tech-srl/code2vec#exporting-the-code-vectors-for-the-given-code-examples

Best,
Uri

**Comment by yilinfang** [comment]
Thank you very much! @urialon
