### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by colebuckleyy** [tech-srl/code2vec#156]
Hello, I successfully preprocessed my dataset to work with code2vec but when I try running the train.sh script I run into a few errors, is there any way I can fix this? 
![code2vec_error](https://user-images.githubusercontent.com/77705009/171322082-c8910ce9-9e3e-43b5-8a67-399981181b37.PNG)

**Comment by colebuckleyy** [comment]
Ok well apparently my preprocessed data somehow got corrupted before I attempted to train and that is why I received those errors but I have one more question. How could I go about labelling the dataset/vectors if I wanted to use this for classification?

**Comment by urialon** [comment]
The method name is taken as the label for classification. So if you retain the same data format, you can replace the method name in the processed data with any label.

See also: https://github.com/tech-srl/code2vec#extending-to-other-languages

Best,
Uri

**Comment by colebuckleyy** [comment]
Ah I see, thank you
