### ISSUE TITLE
Cannot clone java14m_model_trainable 

### ISSUE THREAD

**Issue by hungnt1997** [tech-srl/code2vec#16]

**Comment by urialon** [comment]
I just forgot `wget` there.
What happens when you [click here](https://s3.amazonaws.com/code2vec/model/java14m_model_trainable.tar.gz) or run:
```
wget https://s3.amazonaws.com/code2vec/model/java14m_model_trainable.tar.gz
```

**Comment by hungnt1997** [comment]
i have already cloned it, thank you so much
