### ISSUE TITLE
Original dataset with unprocessed `.java` sources

### ISSUE THREAD

**Issue by abitrolly** [tech-srl/code2vec#160]
I downloaded 6Gb `java14m_data.tar.gz` from [the README.md](https://github.com/tech-srl/code2vec#step-1-creating-a-new-dataset-from-java-sources) and it doesn't contains original source files to reconstruct the model from scratch.

```
$ tar xzvf java14m_data.tar.gz 
data/
data/java14m/
data/java14m/java14m.val.c2v
data/java14m/java14m.test.c2v
data/java14m/java14m.train.c2v
data/java14m/java14m.dict.c2v
```

So is there a dataset with the original `.java` files?

**Comment by urialon** [comment]
Hi @abitrolly ,
Thank you for your interest in our work!

Yes,
The sources of this exact same dataset are not available, but a very similar dataset from the [code2seq paper]() is available here: https://github.com/tech-srl/code2vec#java-large-compressed-72gb-extracted-37gb

Best,
Uri

**Comment by abitrolly** [comment]
Got it,
