### ISSUE TITLE
Converting Vector back to Contexts

### ISSUE THREAD

**Issue by colebuckleyy** [tech-srl/code2vec#163]
I'm wondering if its somehow possible to convert a code vector back into its text format in contexts, is this possible?

**Comment by urialon** [comment]
Unfortunate no :-)

The closest thing I can think about is encoding the entire training set, and saving a database of <example,vector> pairs.

Then at test time, you can encode the test example, and using the test code vector - look for the nearest neighbor training vector from the database.

**Comment by colebuckleyy** [comment]
Ok, thank you
