### ISSUE TITLE
Preprocessor step disposing numbers in (variable) names

### ISSUE THREAD

**Issue by daveymathijssen** [tech-srl/code2vec#164]
Hello,

Thank you for your awesome work!

I have trained some models from scratch using a C# dataset. However, I have a question about the code2vec C# preprocessor.
Some variables within the dataset samples contain a number to make them unique, such as variable_1 and variable_2. However, the [SplitToSubtokens ](https://github.com/tech-srl/code2vec/blob/e7547de9febe969cde7c64f20ebaa0ca5f4673b6/CSharpExtractor/CSharpExtractor/Extractor/Utilities.cs#L94) method removes these variable numbers during preprocessing. I am interested in the purpose of removing these numbers, because when I alter the SplitToSubtokens method and do **not** remove the numbers, all metrics seem to improve.

Best regards,
Davey

**Comment by urialon** [comment]
Hi @daveymathijssen ,
Thank you for your interest in our work!

The C# constructor was contributed by researchers from Microsoft, so I am not sure why did they remove numbers.
I have might removed number in the JavaExtractor as well, I'm not sure.
But if it improves your metrics when you do not remove the numbers, that's great! 

Best,
Uri

**Comment by daveymathijssen** [comment]
HI @urialon,
Thanks for your answer.

In the JavaExtractor, the same is happening in the [normalizeName method](https://github.com/tech-srl/code2vec/blob/master/JavaExtractor/JPredict/src/main/java/JavaExtractor/Common/Common.java#L42) method.
Do you have any clue why?

**Comment by urialon** [comment]
I'm guessing that at the time, 
We did not want to spend embeddings on numbers, as we had ~1M embedding vocabulary anyway.
This is solved in newer models by segmenting tokens into subwords.

You can also check out our newer models 
* code2seq: https://code2seq.org/
* PolyCoder: https://github.com/VHellendoorn/Code-LMs
* CodeBERT that we finetuned on multiple languages: https://github.com/neulab/code-bert-score#backend-model

Best,
Uri

**Comment by daveymathijssen** [comment]
Thank you for your fast responses and insights!
