### ISSUE TITLE
Repeating metric values

### ISSUE THREAD

**Issue by daveymathijssen** [tech-srl/code2vec#166]
Dear Uri,

I am currently using code2vec to train a model to predict vulnerable code. At this moment, I have two labels: good and bad (non-vulnerable and vulnerable). While training models using a variety of data sets, I have found that the metric values (precision, recall, f1, acc) are equal within one epoch. If I use an imbalanced data set instead of a balanced one, the same 'issue' occurs. The training results of one model are shown below. I don't know if this is happening because I only use two labels and I need to change something to 'fix' the metric results or that the metrics are as expected.

> 2022-10-09 22:34:35,061 INFO     Saved after 1 epochs in: models/cwe89-vanilla/saved_model_iter1
> 2022-10-09 22:34:35,515 INFO     Starting evaluation
> 2022-10-09 22:34:36,983 INFO     Done evaluating, epoch reached
> 2022-10-09 22:34:36,983 INFO     Evaluation time: 0H:0M:1S
> 2022-10-09 22:34:36,983 INFO     After 1 epochs -- top10_acc: [0.58969072 1.         1.         1.         1.         1.
>  1.         1.         1.         1.        ], precision: 0.5896907216494846, recall: 0.5896907216494846, F1: 0.5896907216494846
> 2022-10-09 22:35:19,499 INFO     Saved after 2 epochs in: models/cwe89-vanilla/saved_model_iter2
> 2022-10-09 22:35:19,608 INFO     Starting evaluation
> 2022-10-09 22:35:21,108 INFO     Done evaluating, epoch reached
> 2022-10-09 22:35:21,108 INFO     Evaluation time: 0H:0M:1S
> 2022-10-09 22:35:21,108 INFO     After 2 epochs -- top10_acc: [0.70824742 1.         1.         1.         1.         1.
>  1.         1.         1.         1.        ], precision: 0.7082474226804124, recall: 0.7082474226804124, F1: 0.7082474226804124
> 2022-10-09 22:36:04,233 INFO     Saved after 3 epochs in: models/cwe89-vanilla/saved_model_iter3
> 2022-10-09 22:36:04,343 INFO     Starting evaluation
> 2022-10-09 22:36:05,843 INFO     Done evaluating, epoch reached
> 2022-10-09 22:36:05,843 INFO     Evaluation time: 0H:0M:1S
> 2022-10-09 22:36:05,843 INFO     After 3 epochs -- top10_acc: [0.91701031 1.         1.         1.         1.         1.
>  1.         1.         1.         1.        ], precision: 0.9170103092783505, recall: 0.9170103092783505, F1: 0.9170103092783505
> 2022-10-09 22:36:48,562 INFO     Saved after 4 epochs in: models/cwe89-vanilla/saved_model_iter4
> 2022-10-09 22:36:48,655 INFO     Starting evaluation
> 2022-10-09 22:36:50,155 INFO     Done evaluating, epoch reached
> 2022-10-09 22:36:50,155 INFO     Evaluation time: 0H:0M:1S
> 2022-10-09 22:36:50,155 INFO     After 4 epochs -- top10_acc: [0.92989691 1.         1.         1.         1.         1.
>  1.         1.         1.         1.        ], precision: 0.9298969072164949, recall: 0.9298969072164949, F1: 0.9298969072164949
> 2022-10-09 22:37:33,202 INFO     Saved after 5 epochs in: models/cwe89-vanilla/saved_model_iter5
> 2022-10-09 22:37:33,312 INFO     Starting evaluation
> 2022-10-09 22:37:34,780 INFO     Done evaluating, epoch reached
> 2022-10-09 22:37:34,780 INFO     Evaluation time: 0H:0M:1S
> 2022-10-09 22:37:34,780 INFO     After 5 epochs -- top10_acc: [0.93247423 1.         1.         1.         1.         1.
>  1.         1.         1.         1.        ], precision: 0.9324742268041237, recall: 0.9324742268041237, F1: 0.9324742268041237

**Comment by urialon** [comment]
Hi @daveymathijssen ,
Thank you for your interest in our work!

Yes,
I think that if you have only two labels, then `precision == recall == accuracy`.

Regardless of code2vec, you can also try to use `codebert-java`, which is based on BERT, fine-tuned on Java code:
https://huggingface.co/neulab/codebert-java , and further fine-tune it on your vulnerability-detection task.

Best,
Uri

**Comment by daveymathijssen** [comment]
Hi Uri,

Thank you for your response.

It turns out that in my case I had to rewrite the logic to determine the FP, TP, FN, and TN values. I do not have various sub-tokens which need to be taken into account when determining the FP, TP, FN, and TN values, but I only have the tokens 'bad' and 'good'. I have done this for the TopKAccuracyEvaluationMetric class and the SubtokensEvaluationMetric class within the tensorflow_model.py. For example, when a sample labeled 'good' is predicted as 'bad' I want to add 1 to the number of false positives.

**Comment by urialon** [comment]
Right, thanks for letting me know.
I was mistaken in my previous comment, when I said that `precision == recall == accuracy`, this was incorrect.
