### ISSUE TITLE
I don't know how to apply the output files created by astminer.

### ISSUE THREAD

**Issue by Ytz-Ichi** [tech-srl/code2vec#172]
I don't know how to apply the output files created by astminer
I have generated an intermediate file of C++ source code using astminer, but I don't know what to do from here.
The output file structure is as follows:
```
output/
┗cpp/
　┣data/
　┃┗path_contexts.c2s
　┣node_types.csv
　┣path.csv
　┗tokens.csv
```

**Comment by urialon** [comment]
Hi @Ytz-Ichi ,
Thank you for your interest in our work!

I don't know how to process the output of ASTminer.

However, we have a newer model called PolyCoder:
https://github.com/VHellendoorn/Code-LMs

which can be loaded in 2 lines of code using the `Huggingface/transformers` library.

Best,
Uri
