### ISSUE TITLE
Question About Raw Dataset

### ISSUE THREAD

**Issue by HyunaShin** [tech-srl/code2vec#18]
HI, Thanks for your contributions.
I'm concerned with shadowing code2vec, and wishing to do it from the scratch.(including preprocess raw data to preprocessed dataset)
 
So, I wanna ask you that <b>offers raw dataset or not!</b>
Is the only way to get raw dataset is crawling myself? 😢 

I look forward to hearing from you soon.
Sincerely,
Hyuna Shin

**Comment by urialon** [comment]
Hi Hyuna,
Thank you for your interest in code2vec.
Three raw datasets are available on my website:
http://urialon.cswp.cs.technion.ac.il/publications/

Called Java-small, Java-med and Java-large. In my website they are in raw *.java files, not preprocessed.
Best,
Uri

**Comment by HyunaShin** [comment]
Thanks for replying this frivolous question..!
Wish I didn't bothered you a lot.
Thank you again.
Regards,
Hyuna Shin
