### ISSUE TITLE
Queries regarding Java Extractor

### ISSUE THREAD

**Issue by YogishGayatri** [tech-srl/code2vec#184]
Hi code2vec team, 
Thanks for answering the previous question!!
I had one more doubt , I was digging deep into the Java extractor files, How to run these files stand alone with proper arguments as I could not find any information regarding these extractor files(Specifically Java extractor) in the readme.md

**Comment by urialon** [comment]
Hi @YogishGayatri ,
Thank you for your interest in our work.

You mean that you want to run the JavaExtractor separately?

It can be run directly by, for example:
`java -cp JavaExtractor/JPredict/target/JavaExtractor-0.0.1-SNAPSHOT.jar JavaExtractor.App --max_path_length 8 --max_path_width 2 --dir JavaExtractor/JPredict/src/main `

Best,
Uri
