### ISSUE TITLE
Which version of JDK do I need to install before running this project?

### ISSUE THREAD

**Issue by woshizhuchenguang** [tech-srl/code2vec#185]
Hello, which version of JDK do I need to install before running this project?

**Comment by urialon** [comment]
Hi @woshizhuchenguang ,
Thank you for your interest in our work.

Any version which came out in recent 5 years works.

Best,
Uri

**Comment by woshizhuchenguang** [comment]
Thank you !

**Comment by woshizhuchenguang** [comment]
The issue has been resolved.
