### ISSUE TITLE
Queries on ...dict.c2v file

### ISSUE THREAD

**Issue by YogishGayatri** [tech-srl/code2vec#187]
Hi code2vec team,
I have certain doubts regarding the dict.c2v file created while preprocessing
1)Is this file a dictionary of the method names that it has encountered in the training data ? Is there any other info it also stores like Java filenames?
2)When I opened the dict file created for the small java dataset it is stored in a unique format consisting of text , what is the significance of storing it in this format and where in the code is this being done?

**Comment by urialon** [comment]
Hi @YogishGayatri ,
Thank you for your interest in our work!

This file holds different mappings from strings found in the training data (like method names, identifier names), and their integer index

This is the code where it is loaded:
https://github.com/tech-srl/code2vec/blob/master/vocabularies.py#L75

Best,
Uri
