### ISSUE TITLE
Web page don't work.

### ISSUE THREAD

**Issue by hy20191108** [tech-srl/code2vec#189]
This web page (https://code2vec.org/) doesn't work.
It reports this message.
![image](https://github.com/user-attachments/assets/8fd68212-f8f5-47a4-a521-d07fd099286b)

**Comment by urialon** [comment]
Thank you for reporting this.
Yes, we have a problem with the DNS provider, I will let you know once it's
resolved.

In the meantime, you can see the demo at code2seq.org

**Comment by urialon** [comment]
Hi @hy20191108 ,
Thank you again for reporting this.
This is now fixed.

Best,
Uri
