### ISSUE TITLE
what is TARGET_HISTOGRAM_FILE?

### ISSUE THREAD

**Issue by hungnt1997** [tech-srl/code2vec#19]
Hi @urialon,
I'm looking at your preprocessor.sh file but I don't know how this histo.tgt.c2v file is generated so I have two questions:
1/ How this file being generated?
2/ What this file does?
Thanks.

**Comment by urialon** [comment]
Hi,
This histogram (with two others) is created in this line:
https://github.com/tech-srl/code2vec/blob/master/preprocess.sh#L56

It goes over all the examples in the training data and computes a histogram of the possible target names. Using this histogram, the model later builds its vocabulary of possible labels that it can predict.
I hope it's more clear now.
Uri

**Comment by gosuodin** [comment]
Thank you, It's worth for me.
