### ISSUE TITLE
Question on how to export_code_vectors

### ISSUE THREAD

**Issue by ZhaoYi1031** [tech-srl/code2vec#22]
Thanks for the impressive work.

I want to use the word2vec to transfer learning for some other downstream tasks: I have got some java code snippets and I want to get the representation of these methods. I found the parameter export_code_vectors but it seems that it is not implemented. Is that deleted or can you give me some advice on how to use it?

**Comment by zyctinker** [comment]
Hi Zhao,
It seems that you have find the answer, congratulations !
I met the same problem ,too. Can you give me a tip how to do this work?
Thx
ps. maybe we can privately talk in Chinese

**Comment by ZhaoYi1031** [comment]
okay. You can email me or add my qq 291045048.

**Comment by LawrenceLemon1999** [comment]
Hi zhaoyiCC and zyctinker，
I meet the same trouble,can you give me some ideas for that ?
my qq is 497069023. Thank you!

**Comment by urialon** [comment]
Hi @LawrenceLemon1999 ,
Thank you for your interest in our work!

This issue was closed long ago. If you have a question, please create a new issue, describing your problem in details, including the exact command lines that you ran, and the errors messages that you encountered.

Best,
Uri
