### ISSUE TITLE
Fine-tuning for a different task

### ISSUE THREAD

**Issue by rcl0** [tech-srl/code2vec#24]
We are trying to fine-tune the code2vec model for a different task (a binary classification task).

We have previously tried to generate the codevectors for our code-snippets and feed them to a classifier (i.e. using code2vec as a feature extractor). The results haven't been what we expected so we were looking into fine-tuning code2vec with our data. We tried importing the meta_graph and wanted to retrieve the last tensor before classification in order to "connect" it to a binary output. Something along the lines of what is described in the section 'Using a pre-trained graph in a new graph' in https://blog.metaflow.fr/tensorflow-saving-restoring-and-mixing-multiple-models-c4c94d5d7125

Unfortunately we couldn't figure out the name of the tensor we required to be used in get_tensor_by_name(). We even opened the graph in Tensorboard to examine it but were a bit overwhelmed by the size of the graph.

Do you have any pointers as to how to modify the graph for a different classification task all while using the pre-trained weights from training code2vec with java-large?

**Comment by urialon** [comment]
Hi,
I'm not sure, I haven't done it with this project, but I think that the easiest way would be to modify the creation of the graph in the python code.
Look, in the code, at how we build the test graph, and load the saved weights. I think you can do the same, and just change the code that creates the test/training graph.

In other words, I think it's easier if you don't take the graph structure from the saved file, but re-build it in python instead.

Best,
Uri

**Comment by urialon** [comment]
And don't forget to use "trainable=False" when you "get_variable" that you want to freeze.

**Comment by rcl0** [comment]
Thanks, we'll give that a try!
