### ISSUE TITLE
AST Visualizer From Demo Website

### ISSUE THREAD

**Issue by esstorm** [tech-srl/code2vec#25]
Hi. Is the source code for the AST visualizer from the demo website available? I mean the script to which you feed the output of the /predict endpoint. It is very nice and I would like to use it for a university project if possible. Thank you!

**Comment by urialon** [comment]
Hi,
You mean the serialization of the AST, or the JavaScript frontend?

Uri

**Comment by esstorm** [comment]
Hi Uri,
Thanks for replying. I mean the JS frontent.

Esteban

**Comment by guywald1** [comment]
Hey Esteban,

Thank you so much for your kind words and for your interest in code2vec! I was in charge of the front-end for this project.
As we have no current plans (yet) to make the source code for the site open source, I can tell you that it was mostly built with React, D3 and a custom fork of [react-d3-tree](https://github.com/bkrem/react-d3-tree) with some domain-specific logic for our visualization.

If you have any specific question I'd be happy to assist! Thanks again.

**Comment by guywald1** [comment]
@esstorm

Hey Esteban,

Thank you so much for your kind words and for your interest in code2vec! I was in charge of the front-end for this project.
As we have no current plans (yet) to make the source code for the site open-source, I can tell you that it was mostly built with React, D3 and a custom fork of [react-d3-tree](https://github.com/bkrem/react-d3-tree) with some domain-specific logic for our visualization.

If you have any specific question I'd be happy to assist! Thanks again 😄

**Comment by esstorm** [comment]
@guywald1  Thank you for your reply! I will check out  react-d3-tree then :) I think it might be enough for my purposes

**Comment by hsellik** [comment]
Hi @guywaldman ,

It seems that it is not too hard to use react-d3-tree (for example JSON files) and to serialize a piece of Java code (to JSON) using JavaParser.

However, I have some specific questions:
1) How were the AST paths outputted from the model tied with the serialized AST from the JavaParser?
2) Are there any specific pitfalls I should look out for while converting a JSON that was retrieved from JavaParser to JSON that is required by react-d3-tree?

**Comment by urialon** [comment]
Hi @hsellik ,
We perform the parsing (using JavaParser) in the backend, and the backend returns a JSON to the frontend that contains the AST, the predictions, and the mostly-attended paths.

You can see the backend's response (actually this is code2seq's backend) by running from the terminal:
```
curl -X POST https://djz6amor4b.execute-api.us-east-1.amazonaws.com/prod/predict -d '{"code":"public boolean f(Set<String> set, String value) {  for (String entry : set) {    if (entry.equalsIgnoreCase(value)) {  return true ;    }  }  return false;  }   "}'
```

Guy wrote the frontend code that takes the backend's response and displays the AST using react-d3-tree.
I hope that answers the first question, or did I miss anything?

(I don't know the answer to the second question)

Best,
Uri

**Comment by hsellik** [comment]
Hi @urialon ,

Okay, makes sense. Thanks for the quick reply. I am mostly interested in the conversion from JavaParser generated JSON to [JSON format required by react-d3-tree](https://github.com/bkrem/react-d3-tree/blob/master/docs/examples/data/json-example.json) (with children[] list containing child nodes, etc.) that is also present in the backend response. Is this code available somewhere?

**Comment by guywaldman** [comment]
Hi @hsellik,

The code for the website frontend is not currently open sourced (hopefully eventually will be) but I can guide you through how I transformed the AST into data in the format that `react-d3-tree` required.
When I wrote the code for the website, there were some missing features from `react-d3-tree` (IIRC having to do with collapsing nodes) so I forked a version of my own. For a recent similar project to `code2vec` I was able to use `react-d3-tree` without having to fork.

Can you ping me at `guywald1@gmail.com`?

Thanks!
