### ISSUE TITLE
provide Dockerfile for quick start?

### ISSUE THREAD

**Issue by wangluochao902** [tech-srl/code2vec#28]
Can you guys provide a Dockerfile to start easily?

**Comment by urialon** [comment]
Hi,
Currently we don't have a docker file, but is there a specific step you're having trouble with?

**Comment by jeroenherczeg** [comment]
I have used https://www.tensorflow.org/install/docker with success!

```
docker run --runtime=nvidia -it -v $(realpath ~/Code):/code -u $(id -u):$(id -g) tensorflow/tensorflow:2.0.0b1-gpu-py3 bash
```
