### ISSUE TITLE
Size of code vector is 384 and not 128

### ISSUE THREAD

**Issue by mmsbrggr** [tech-srl/code2vec#32]
In the code2vec paper published at POPL19, it says that the size of the code-vector is d with d=128. Moreover, also the vectors of the contexts after the dense layer should, according to the paper, have size 128. However, when debugging the code I noticed that their size is 3*d=384. Am I missing something?

Thank's for answering :)

**Comment by basedrhys** [comment]
The output code vector is made up of three 128-dim vectors concatenated:

- The source leaf embedding
- The path embedding
- The target leaf embedding

This gives the final size of 384

**Comment by mmsbrggr** [comment]
Actually, I think the code vector is an aggregation of up to 200 combined context vectors (aggregated with soft-attention). According to the paper all of these combined context vectors are of dimensionality 128 (as well as the final code vector). If I read the paper correctly the only vectors of size 384 are the context vectors right at the start of the pipeline, where they are - as you described - a concatenation of 3 128-dim vectors. I was wondering what the motivation behind changing all of those vectors dimensions to 384 was, in comparison to the model proposed in the paper.

**Comment by urialon** [comment]
Hi,
Thanks for noticing.

See here:
[https://github.com/tech-srl/code2vec/issues/29#issuecomment-519087193](https://github.com/tech-srl/code2vec/issues/29#issuecomment-519087193)

Let me know if you have any other questions!

**Comment by mmsbrggr** [comment]
Hi,
perfect. thanks for clarifying.
