### ISSUE TITLE
Question: Is there already a pre trained keras model?

### ISSUE THREAD

**Issue by s0l4s** [tech-srl/code2vec#38]
I have read there is already a keras implementation but as far as I understand this one is not compatibel with the weights of the pre trained models on S3. Is this correct? I'm wondering because me and my study group want to research if it is possible to use this network for transferlearning by replacing the final layer. However we find it easier to work with keras if possible.

**Comment by urialon** [comment]
@eladn do you have an idea? I remember that we talked about it..
Is it possible to load a TF model with the TF.keras implementation?
If it requires merging PAD and UNK this is fine.
I have a script somewhere that changes the names of saved variables if this is the problem

By the way @s0l4s , if you are willing to work in TF, [code2seq](www.code2seq.org) has a better encoder and is more likely to succeed in transfer learning.

**Comment by eladn** [comment]
> Is it possible to load a TF model with the TF.keras implementation?
1. We haven't yet published any trained Keras model. We may do so in the future.
2. The published code does not currently support loading the trained TF weights using the Keras implementation.
3. However, it is technically possible to write a script that does it. To do so, one might have to change the names of the weights as you suggested. I would (i) check the names of the variables both in the Keras & TF implementations; then (ii) create a mapping (TFImplVariableName->KerasImplVariableName); and finally (iii) write a script that loads a weights file of the TF model and outputs a new one after applying the mentioned mapping.
4. Notice also that except the variable names, the Keras implementation uses different saving mechanism than the TF implementation. This means that you also might have to make additional adaptations (like having the checkpoints file). I would train the Keras model for one epoch on a tiny dataset just to let it save a checkpoint to understand its structure.

> If it requires merging PAD and UNK this is fine.
Indeed. But the default configuration set it that way, so no need to change anything. More information about it: There is a configuration parameter named [`SEPARATE_OOV_AND_PAD`](https://github.com/tech-srl/code2vec/blob/c98e8f786b7262e56c93e520d039fb7aa5d0f7ef/config.py#L70) that should be set to `False` (this is actually the default value). Moreover, I believe that all the default parameters values matches the configuration used to train the published trained TF model.

**Comment by s0l4s** [comment]
Thanks for the surgestions I will look at code2seq and else try your keras surgestions. Anyway thanks

**Comment by urialon** [comment]
Hi @s0l4s ,
If it helps, here is a script I wrote once to rename variables in a saved model.
You need to specify the old and new names in the `vars_to_rename` dictionary and run with the flag `--dry_run` first.
I haven't checked it recently, so if you use it - backup your saved model files first.

Let us know how it goes,
Uri
