### ISSUE TITLE
Cannot run preprocess.sh for raw data

### ISSUE THREAD

**Issue by dungqut** [tech-srl/code2vec#39]
Hello Urialon

I tried to run preprocess.sh for raw java, but It always gives me errors No such file or directory: 'java': 'java'

Could you check or give me solutions?

I really look forward to hearing from you

Regards
Dung

**Comment by dungqut** [comment]
Hello @danglotb 

If you run preprocess.sh file for raw data successfully, can you share you solution? I really appreciate you help

Regards
Dung

**Comment by urialon** [comment]
Hi,
There is probably no such directory as the directory you provided.

Please copy and paste the directory you tried to run preprocess on, and check if it really exists. Are you on Windows or Linux?

Everything will work, don't worry, you are probably doing something wrong. There is no need to "share a solution" because there is no specific solution.

**Comment by dungqut** [comment]
Hello @urialon  I am working on ubuntu

I have checked carefully I have folder "/home/dung/Downloads/hpc/CONFERENCES_JOURNAL/datasets/java"

And I have three subfolders inside (test, training, and validation)

I think I set something wrong in:

command1 = ['java', '-Xmx100g', '-XX:MaxNewSize=60g', '-cp', args.jar, 'JavaExtractor.App',
               '--max_path_length', str(args.max_path_length), '--max_path_width', str(args.max_path_width),
               '--dir', dir, '--num_threads', str(args.num_threads)]

this command below may not recognize 'java' in command1:

 sleeper = subprocess.Popen(command, stdout=outputFile, stderr=subprocess.PIPE)

Am I missing something here or could you show me your file you already set up?

I really need your help

**Comment by urialon** [comment]
Oh right, you just need to install **JDK** using apt-get and verify that you can run "java".

**Comment by urialon** [comment]
It is mentioned in the Requirements section of the README.
https://openjdk.java.net/install/

**Comment by dungqut** [comment]
hell @urialon  Thanks you a lot, I am trying now and let you know if I am still facing problem
