### ISSUE TITLE
Error on evaluating a trained model

### ISSUE THREAD

**Issue by nitishMehrotra** [tech-srl/code2vec#4]
When I follow the steps given in the README.md I get the following error:

<img width="1680" alt="screenshot 2018-11-27 at 4 49 34 pm" src="https://user-images.githubusercontent.com/3133988/49078642-8f527f80-f264-11e8-8a1f-b37bdc891469.png">
<img width="1676" alt="screenshot 2018-11-27 at 4 49 49 pm" src="https://user-images.githubusercontent.com/3133988/49078644-8feb1600-f264-11e8-84f8-5eae069ac649.png">

I am using the release model from the s3 link provided and I also renamed `saved_model_iter8.release.data-00000-of-00001` to `saved_model_iter8.release` as recommended in README.md but still I get the same error

**Comment by urialon** [comment]
Hi Nitish,
*There is no need to rename anything*. This is probably the cause.
A saved model consists of several files having the same prefix, which is "saved_model_iter8.release" in this case:
`saved_model_iter8.release.index`
`saved_model_iter8.release.data-00000-of-00001`
`saved_model_iter8.release.meta`
and an additional `dictionaries.bin` file.

When you load a trained model for evaluation, as in:
`python3 code2vec.py --load models/java14_model/saved_model_iter8.release --test data/java14m/java14m.test.c2v`

You just need to specify the *prefix* of `saved_model_iter8.release`, without the `.meta`, `.index`, and `.data-0000...` suffixes.

Let me know if it works now.

**Comment by nitishMehrotra** [comment]
It worked Uri. Thanks a lot!

**Comment by urialon** [comment]
I'm happy to hear that. 
Let me know if there's any other issue.

**Comment by AisheeDasgupta** [comment]
i get no such file or directory error in the path "data/java14m/java14m.test.c2v"
I think this file is not provided in the repository
Thanks in advance

**Comment by urialon** [comment]
@AisheeDasgupta 
See here: 
[https://github.com/tech-srl/code2vec#download-our-preprocessed-dataset-of-14m-examples-compressed-63gb-extracted-32gb](https://github.com/tech-srl/code2vec#download-our-preprocessed-dataset-of-14m-examples-compressed-63gb-extracted-32gb)
