### ISSUE TITLE
Adpat code to new language such as C/C++

### ISSUE THREAD

**Issue by dungqut** [tech-srl/code2vec#40]
Hello I really wish to adapt your code to C/C++

Do you have any idea to do this, I really appreciate you help

I look forward to hearing from you

**Comment by urialon** [comment]
Hi,
There is a C adapter by the CMU-SEI team, see:
https://github.com/tech-srl/code2vec/blob/master/README.md#extending-to-other-languages

**Comment by dungqut** [comment]
Hello @urialon

Thanks you a lot for your quick response, I already checked this, but is this possible to work on C++ because it seems that this is only for C. I look forward to hearing from you

**Comment by urialon** [comment]
Check if PathMiner is able to process C++ (link in the same place in the README).

Otherwise, you can implement it yourself, there are instructions in the same place in the README. Good luck!

**Comment by dungqut** [comment]
Hello @urialon I have checked https://github.com/cmu-sei/code2vec-c
and try to run, I have followed carefully the instruction but always face problems:

Extracting paths from data set...
Finished extracting paths from data set
Calculating lines
Extracted no lines. (missing source files?)

Have you tried to run this code or can you give solutions?

**Comment by urialon** [comment]
Sorry, I have no idea, you can ask them...

**Comment by dungqut** [comment]
Hello @urialon 

Thanks you a lot for your reply

I will ask them now

Do you have plan to extend to other languages?

**Comment by urialon** [comment]
Sorry, not at the moment. But if you manage to implement an extension, I would be happy to refer to it from this repository.
