### ISSUE TITLE
Some questions about Dataset

### ISSUE THREAD

**Issue by BUCTwangkun** [tech-srl/code2vec#43]
Hi, when I begin to checked the dataset "java14m.dict.c2v", I found the format like this 
"[path, -1354628, 30]". "Path" and "30" are "Xs" and "Xt", and "-1354628" is the path. And the number is node.
I have a question about that:
why the path < 0 ? because of "↑"  "↓" ? So could you tell me how to represent it?
I'm confused about that, although the Definition2 and Defination3 have mentioned it.

Thank you~

**Comment by urialon** [comment]
Hi,
The negative number is just the hashCode() of the path string, so we can keep numbers instead of long strings.
So instead of using the long string representing the path, we're just using its hash.
Does that make sense?

**Comment by BUCTwangkun** [comment]
Thank you for your reply !!! Got it !!
I also have questions about the format of raw data. Do it represent one method in a line ? 
And the JavaExtractor is a package that changes method to paths, is right? I want to how to get AST in your project or Could you tell me tools to get AST

**Comment by urialon** [comment]
Yes, one method in a line.
And yes, JavaExtractor is the package that extracts paths from methods. As an intermediate step, it parses the code to get the AST using [JavaParser](https://javaparser.org/).

**Comment by BUCTwangkun** [comment]
Thank you deeply~

**Comment by Ceceu** [comment]
> Thank you for your reply !!! Got it !!
> I also have questions about the format of raw data. Do it represent one method in a line ?
> And the JavaExtractor is a package that changes method to paths, is right? I want to how to get AST in your project or Could you tell me tools to get AST

Could you point me where I find this raw dataset? Using it would it be possible to pairwise the original definition of the method with its representation after code2vec preprocessing?

**Comment by urialon** [comment]
Hi @Ceceu ,
I think that we talked about it in another issue?

Feel free to open a new issue if you have further questions.
