### ISSUE TITLE
Error when MAX_CONTEXTS in config.py is changed

### ISSUE THREAD

**Issue by anjandash** [tech-srl/code2vec#45]
I am experimenting with code2vec for a binary classification problem for java methods, where the feature extractor generates the path vectors from AST as expected. The value of MAX_CONTEXTS in config.py is first set to 400. The preprocessing step works fine too with MAX_CONTEXTS set to 400 (in preprocess.sh) as the expected *.c2v files are generated. 

Then when I start training (train.sh), I get the following error: 

`File "/home/lv71161/akarmakar/miniconda3/envs/c2v/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 201 fields but have 401 in record 0` 

Could you tell what might be the issue here? 
What am I doing wrong in the case where I set MAX_CONTEXTS = 400?
MAX_CONTEXTS = 200 works perfectly fine!

Here is the screenshot for your reference:
![Screen Shot 2019-09-30 at 5 02 09 PM](https://user-images.githubusercontent.com/16762385/65891036-3089f500-e3a4-11e9-9b94-3c447d1ca73f.png)

**Comment by urialon** [comment]
Hi,
The only thing I can think of is that you did not `preprocess.sh` the dataset with MAX_CONTEXTS=400.

Can you please run the following bash command, and replace MYFILE with the name of the training.c2v file, and paste the result here?
 
```
cat MYFILE | head -5 | tr ' ' '|' | awk -F'|' '{print NF}'
```

**Comment by anjandash** [comment]
Hi @urialon 

It seems the c2v file has 400 entries. 
I ran the above command on my train.c2v file and here is the result:
![Screen Shot 2019-10-01 at 9 58 56 AM](https://user-images.githubusercontent.com/16762385/65944606-5eb61600-e432-11e9-88c3-cf40be4a2a02.png)

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 201 fields but have 401 in record 0`

Perhaps it has something to do with tensorflow?

**Comment by urialon** [comment]
Hi,
And are you sure that MAX_CONTEXTS is 400 as well in config.py?

**Comment by anjandash** [comment]
[RESOLVED]

Okay, I cross-checked the files on the Code2Vec GitHub repo (the current version) with the code2vec files I have on my machine, and it turns out I have been running a version where the code2vec.py collects the MAX_CONTEXTS from common.py! 

I changed the values there and it works fine now. Thank you. :)
This issue, I suspect was mainly because of a merge failure at some point.

**Comment by urialon** [comment]
Great! Glad to hear.
Let me know if you have any more questions.

By the way, [code2seq](www.code2seq.org) is better than code2vec, even for binary classification, because it has a much better encoder.
