### ISSUE TITLE
Finding semantic code clones

### ISSUE THREAD

**Issue by nickshevr** [tech-srl/code2vec#46]
Hi, am I right that I can use ur NN for finding clones with similar semantics via vectors distance?

Thx for the answer.

**Comment by urialon** [comment]
Hi,
Maybe. 
It depends on your definition of clones.

Best,
Uri

**Comment by nickshevr** [comment]
@urialon do u have any papers about this?

**Comment by urialon** [comment]
Hi,
There are a few listed here:
[https://ml4code.github.io/papers.html](https://ml4code.github.io/papers.html)
But I haven't read them.

Additionally, you can check out our newer paper [code2seq](https://code2seq.org).
Although code2seq is able to generate sequences, its encoder is also much better than code2vec's.

Best,
Uri

**Comment by nickshevr** [comment]
@urialon thanks a lot!
