### ISSUE TITLE
This website (https://code2vec.org/) don't generate the AST

### ISSUE THREAD

**Issue by BUCTwangkun** [tech-srl/code2vec#49]
Hi~
When I used some examples in java-small dataset just like this, 
@Test public void f(){   
    assert MIDDLE_VERSIONS_ENTITY_NAME.equals(metadata().getEntityBinding(MIDDLE_VERSIONS_ENTITY_NAME).getTable().getName()); 
}
the website didn't show me the AST, I want to know whether the example must be out of the training dataset.

Thanks~

**Comment by urialon** [comment]
Hi @BUCTwangkun ,
The model is supposed to produce a prediction and an AST for any snippet, whether or not it is was in the training set. So the question of whether or not the example is in or out of the training set doesn't matter.
I think there is a problem with parsing specifically the `assert` statement, let me check.

**Comment by urialon** [comment]
Hi @BUCTwangkun ,
There was indeed a problem in serializing the assert statement. 
This is now fixed, I checked your example and it produces an AST.
Thanks a lot for reporting this.

Best,
Uri

**Comment by BUCTwangkun** [comment]
Wow，it's my pleasure~
