### ISSUE TITLE
Questions on code2vec's usage

### ISSUE THREAD

**Issue by danglotb** [tech-srl/code2vec#5]
Hi,

First of all, I would like to thank you for this good job, it is awesome!

Then I would like to ask two questions:

1. I want to train a model of the name convention of the test suite. What should I do to train the model? Should make the scripts pointings to the root of the test suite, _e.g._ `src/test/java/` in a typical maven project? Or Should I extract each test method from their test classes and create a large fake java file with all (and only) the test methods, such as the Input.java file when we predict the label of a method?

2. What would you suggest in the case that we do not have a lot of data to train the model?

Thank you again.

**Comment by urialon** [comment]
Hi Benjamin,
Thanks for using code2vec!

1. Yes, in the file [preprocess.sh](https://github.com/tech-srl/code2vec/blob/master/preprocess.sh#L21) point the training dir to the directory containing the test methods (e.g., `src/test/java/`). Make sure to pull first, I just submitted a fix that enables extracting paths from a single directory which not necessarily contains subdirectories (previously, it could extract only from a directory that _must_ contain subdirectories). You definitely do _not_ need to create a fake java file.

2. Maybe you can train a model on millions of test-only methods? or are you interested in the conventions of a specific project?

**Comment by urialon** [comment]
Another option is to train a model on a large corpus, and then fine-tune the weights for a specific project or task.

For example, train on our large general corpus, and then fine-tune the weights by training on test-only files of a specific project.
Or:
Create your own large corpus of test-only files (from many projects) and then fine tune on a specific project.

**Comment by danglotb** [comment]
Hi @urialon 

Thank you for the answer!

> Maybe you can train a model on millions of test-only methods? or are you interested in the conventions of a specific project?

I still think about it. I do not know what is the best: training the model to generalize overall all test suites or training a model for each test suite, in order to have dedicated models for each test suite.

> Create your own large corpus of test-only files (from many projects) and then fine tune on a specific project.

That looks great, however, I do not have (yet) the background on this. I must document myself.

Thank you very much! :)

**Comment by urialon** [comment]
I can't tell for sure, but I guess that if you have a small corpus (i.e., the tests from a single project) it might be more beneficial to train the model on on a larger corpus first.

Basically what you need to do is run "preprocess.sh" twice and create two datasets (a general-large one and a specific-small one). Then train the model on the large dataset until it converges or almost-converges. Afterwards, load the trained model and let it continue training on the small dataset (using the flags: `--load <trained_model>`, `--data <small_dataset` and `--save <new_name>`).

No problem, let me know if you have any more questions.

**Comment by danglotb** [comment]
Hello, I reopen this issue since I have a new question:

As you suggested, I can use an already trained model and use my own dataset in order to converge faster.

What I did to do that is:

1. Get the already trained model `java14m_model` from the `README`:
```bash
wget https://s3.amazonaws.com/code2vec/model/java14m_model.tar.gz
tar -xvzf java14m_model.tar.gz
```

2. Preprocess my own dataset:

```bash
wget https://zenodo.org/record/2567792/files/benchmark.zip
unzip benchmark.zip
```

replace in `preprocess.sh`:
```bash
TRAIN_DIR=benchmark/training/
VAL_DIR=benchmark/validation/
TEST_DIR=benchmark/test
DATASET_NAME=dspot-prettifier-exp-march-2019
``` 
and run it.

3. train the already trained model with new data:
```bash
type=dspot-prettifier-exp-march-2019
dataset_name=dspot-prettifier-exp-march-2019
trained_model=models/java14_model/saved_model_iter8
python3 -u code2vec.py --load ${trained_model} --data ${data} --test ${test_data} --save ${model_dir}/saved_model
```

The problem is that I obtain the following error:
```txt
Loading model weights from: models/java14_model/saved_model_iter8
Traceback (most recent call last):
  File "code2vec.py", line 38, in <module>
    model.train()
  File "/tmp/code2vec/model.py", line 83, in train
    self.load_model(self.sess)
  File "/tmp/code2vec/model.py", line 409, in load_model
    self.saver.restore(sess, self.config.LOAD_PATH)
  File "/home/bedanglot/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1538, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: models/java14_model/saved_model_iter8
```

Could you please, give me some hints on what I'm doing wrong?

**Comment by urialon** [comment]
Hi Benjamin,
Yes, as I noted [here](https://github.com/tech-srl/code2vec#note), this trained model is in a "released" state, which means it can't be trained anymore (with the upside is that it is much lighter).

I can't find the non-released saved model, I think I accidentally deleted it. Can you train a new model for a few hours on the preprocessed dataset ([here](https://github.com/tech-srl/code2vec#download-our-preprocessed-dataset-of-14m-examples-compressed-63gb-extracted-32gb))?

**Comment by danglotb** [comment]
>Yes, as I noted [here](https://github.com/tech-srl/code2vec#note), this trained model is in a "released" state, which means it can't be trained anymore (with the upside is that it is much lighter).

Sorry, I missed this valuable information.

> I can't find the non-released saved model, I think I accidentally deleted it. Can you train a new model for a few hours on the preprocessed dataset ([here](https://github.com/tech-srl/code2vec#download-our-preprocessed-dataset-of-14m-examples-compressed-63gb-extracted-32gb))?

Give me a shot, I'm gonna launch the training right now. I'll keep you update.

Thank you very much :-)

**Comment by urialon** [comment]
Yes! The `train.sh` is supposed to work if you downloaded the preprocessed dataset. 
`train.sh` is currently pointing to `data/java14m/java14m.{train,test,val,dict}.c2v`, just verify that after you extract the preprocessed dataset, these files exists in this relative path.
Let me know how it goes.

**Comment by urialon** [comment]
Hi @danglotb,
Did you manage to train the model?
I found a non-released trained model, it just weights 4.5 GB. Let me know if you need it and I'll upload it somewhere.

**Comment by danglotb** [comment]
Hello @urialon 

I tried, but all the node on our clusters with GPUs was reserved.

I launched the training this morning but it keeps log something like:

```
Average loss at batch 46000: 0.000739,  throughput: 4373 samples/sec
Number of waiting examples in queue: 300000
Average loss at batch 46100: 0.000742,  throughput: 4397 samples/sec
Number of waiting examples in queue: 299717
Average loss at batch 46200: 0.000782,  throughput: 4361 samples/sec
Number of waiting examples in queue: 300000
Average loss at batch 46300: 0.000815,  throughput: 4383 samples/sec
Number of waiting examples in queue: 293595
Average loss at batch 46400: 0.000846,  throughput: 4382 samples/sec
Number of waiting examples in queue: 290755
```

Is this the normal behavior? I think I could use your trained model. Thank you very much.

**Comment by urialon** [comment]
Oh yeah, this is great and very fast. Is it a Titan X?

Since you are already in batch ~46k, you already have about 3 saved model versions.
Check the directory "models/java14m" and you'll find the new models there.
Search the console output for "F1" to see the current F1 score, it should be ~58 in the third epoch.

You can either continue training until you reach the max F1 score, or stop now and get the current model, it should be good enough (it is supposed to be 99% converged at this point).

**Comment by danglotb** [comment]
Hello, yesterday I had some issue to retrieve the model. 

Then, I re-trained the model. It is available [here](https://zenodo.org/record/2577346).

The first archive, `java14m_iter7` contains all the files of the model for 7 iterations.

The second one, `trained_model` should contain only the model for the 8th iteration.

After 8 iterations, I stopped the training.

I'll now try to apply to the protocol we discuss.

Thank you.

**Comment by danglotb** [comment]
Hello.

I train the already trained model with my own dataset (of test methods).

Here, an excerpt of the output:

```txt
Accuracy after 6 epochs: [0.17413757 0.19572449 0.20486636 0.21056549 0.21391519]
After 6 epochs: Precision: 0.43194554184647177, recall: 0.19215253669035182, F1: 0.2659820128671999
Average loss at batch 1100: 0.000170,   throughput: 2157 samples/sec
Number of waiting examples in queue: 70000
Done training
```

I ran:
```bash
python3 code2vec.py --load models/dspot-prettifier-exp-march-2019/saved_model_iter6 --test data/dspot-prettifier-exp-march-2019/dspot-prettifier-exp-march-2019.test.c2v
```

and obtain:

```txt
Evaluation time: 0H:0M:47S
[0.1641911  0.18513131 0.19336192 0.19919991 0.20358319 0.20683715
 0.20934461 0.21212005 0.21376617 0.2154123 ]
Precision: 0.4146601385384097, recall: 0.18096817645329577, F1: 0.25197018754963657
```

WDYT?

For me, this is not very good. The precision seems to be very low, isn't? But the train did only 6 epochs. 

How can I increase the precision?

Thank you.

**Comment by urialon** [comment]
Hi Benjamin,
It's difficult to tell.
First, does it perform better than training on your dataset from scratch? (without taking the pretrained model)? 

Second, you need to look at the precision/recall/F1 scores across different epochs and see if it keeps improving from epoch to epoch. If it does keep improving, keep training. 
Finally, I would look at the correct and mistaken predictions (they are logged in the file `log.txt`) and try to get better insights.

**Comment by danglotb** [comment]
>First, does it perform better than training on your dataset from scratch? (without taking the pretrained model)?

I does, I was at  `< 0.20` in term of precision.

> Second, you need to look at the precision/recall/F1 scores across different epochs and see if it keeps improving from epoch to epoch. If it does keep improving, keep training.
```txt
Accuracy after 1 epochs: [0.17118333 0.1934681  0.20193538 0.20779734 0.21133313]
After 1 epochs: Precision: 0.43748455646157647, recall: 0.19146646768428852, F1: 0.26635976245011866
...
Accuracy after 2 epochs: [0.17516109 0.19539882 0.20421503 0.21063528 0.21484566]
After 2 epochs: Precision: 0.4362518265952265, recall: 0.19374290195230112, F1: 0.26832191139572337
...
Accuracy after 3 epochs: [0.17462607 0.19653865 0.20500593 0.21044918 0.21475261]
After 3 epochs: Precision: 0.43238812314044567, recall: 0.1925437624040796, F1: 0.2664406728927203
...
Accuracy after 4 epochs: [0.17462607 0.19605015 0.20591314 0.21047245 0.21435716]
After 4 epochs: Precision: 0.4319286871961102, recall: 0.1931180306946863, F1: 0.266902345326537
...
Accuracy after 5 epochs: [0.17392821 0.19616646 0.2053316  0.21065854 0.21410128]
After 5 epochs: Precision: 0.43213148881062174, recall: 0.19307704371055748, F1: 0.26690189277277754
...
Accuracy after 6 epochs: [0.17413757 0.19572449 0.20486636 0.21056549 0.21391519]
After 6 epochs: Precision: 0.43194554184647177, recall: 0.19215253669035182, F1: 0.2659820128671999
```

It seems quit stable...

> Finally, I would look at the correct and mistaken predictions (they are logged in the file `log.txt`) and try to get better insights.

I'm gonna do that. Thank you.

**Comment by urialon** [comment]
I also see that your precision is much higher than the recall.
I am guessing that a typical name is "test_something_something_something" and the model just predicts "test" and this way gets a high accuracy without recall.
If this is the case you might want to try the [code2seq model](www.code2seq.org) which is able to generate more complex predictions.

**Comment by danglotb** [comment]
Okay, I'm gonna try [code2seq](https://github.com/tech-srl/code2seq).

Do I have to train again the whole model?

I tried to reuse the model that I trained and I have the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'trained_model/saved_model_iter8.dict'
```

I guess the files are not the same. I'm gonna train again the model use code2seq.

Thank you for your help, it is very valuable.

**Comment by urialon** [comment]
Yes, they are different models, thus code2seq needs to be trained from scratch. The usage is very similar to this project.

**Comment by danglotb** [comment]
I have some issue with TensorFlow and Cuda. It seems that now, TensorFlow is looking for Cuda 10.

On the cluster, I have only Cuda 9. I'm looking for support on this.

I'll report the training of the new code2seq's model and make it available, as I did for the trained model of code2vec.

**Comment by dungqut** [comment]
Hello @urialon  I tried many times to run preprocess.sh to work on raw datasets (java-small).
I have set

TRAIN_DIR=/home/dung/Downloads/hpc3/Deakin/code2vec-master/pldi18_js/js/js_training
VAL_DIR=/home/dung/Downloads/hpc3/Deakin/code2vec-master/pldi18_js/js/js_test
TEST_DIR=/home/dung/Downloads/hpc3/Deakin/code2vec-master/pldi18_js/js/js_test
DATASET_NAME=js

but it always has errors FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java' 

Could you help me or give me any idea?

**Comment by urialon** [comment]
Hi,
Yes, it seems that you're trying to preprocess Java**Script** files.
To use Java-small, see:
https://github.com/tech-srl/code2seq/#java

**Comment by dungqut** [comment]
@danglotb hell Dang can you check the link 
wget https://s3.amazonaws.com/code2vec/model/java14m_model.tar.gz

I cannot download it

**Comment by dungqut** [comment]
Hello @urialon  even I run with code2seq, the same error 

I have set in preprocess.sh file as follows:

TRAIN_DIR=/home/dung/Downloads/hpc/CONFERENCES_JOURNAL/datasets/java/training
VAL_DIR=/home/dung/Downloads/hpc/CONFERENCES_JOURNAL/datasets/java/validation
TEST_DIR=/home/dung/Downloads/hpc/CONFERENCES_JOURNAL/datasets/java/test
DATASET_NAME=java

but same errors coming:
No such file or directory: 'java': 'java'

Do you face this issue before? or could you explain or give me any solution?

Thanks you a lot

Regards
Dung

**Comment by urialon** [comment]
Hi,
It tells you that the path you provided does not exist.

**Comment by dungqut** [comment]
Hello @urialon I checked carefully I have /home/dung/Downloads/hpc/CONFERENCES_JOURNAL/datasets/java

But Could you give me more solution, what is DATASET_NAME I should put, just any name?

I have set as follows:

Could you kindly check?

TRAIN_DIR=/home/dung/Downloads/hpc/CONFERENCES_JOURNAL/datasets/java/training
VAL_DIR=/home/dung/Downloads/hpc/CONFERENCES_JOURNAL/datasets/java/validation
TEST_DIR=/home/dung/Downloads/hpc/CONFERENCES_JOURNAL/datasets/java/test
DATASET_NAME=java
MAX_DATA_CONTEXTS=1000
MAX_CONTEXTS=200
SUBTOKEN_VOCAB_SIZE=186277
TARGET_VOCAB_SIZE=26347
NUM_THREADS=64
PYTHON=python3

**Comment by dungqut** [comment]
Hello @urialon  I think I missed something in this settings "command = ['java', '-Xmx100g', '-XX:MaxNewSize=60g', '-cp', args.jar, 'JavaExtractor.App',
               '--max_path_length', str(args.max_path_length), '--max_path_width', str(args.max_path_width),
               '--dir', dir, '--num_threads', str(args.num_threads)]"

could you check is this correct settings, or which file you used to process the input for code2vec?

I really look forward to hearing from you

Regards
Dung

**Comment by urialon** [comment]
Please use a new issue, this one is closed and will make your questions easy to miss.
