### ISSUE TITLE
Cannot get code2vec for short methods

### ISSUE THREAD

**Issue by hussien89aa** [tech-srl/code2vec#55]
When I feed tool with a short method like this one.

```
@Override
public void andReturn(Object value) {
this.throwWrappedIllegalStateException();
}
```

I donot get the cod2vec, why?

**Comment by urialon** [comment]
Hi,
Can you please provide:
1. Your TF version
2. What did you run?
3. Do other examples work?
4. What happens when you feed this example?

**Comment by hussien89aa** [comment]
Thanks for answering the problem is resolved after i clone the last version of code2vec, i was using old version.
