### ISSUE TITLE
I would like to ask questions about the extraction of AST

### ISSUE THREAD

**Issue by wblovecoding** [tech-srl/code2vec#58]
Hi, I want to ask about the estraction of AST in your code.
Do you write the code manually or generate it with some framework?
I haven't fully understood your code, so i have to  ask you here.
Thank you so much.

**Comment by urialon** [comment]
Hi,
The AST is generated using [JavaParser](https://javaparser.org/). Parsing happens [here](https://github.com/tech-srl/code2vec/blob/master/JavaExtractor/JPredict/src/main/java/JavaExtractor/FeatureExtractor.java#L61).

Best,
Uri
