### ISSUE TITLE
Create new label for source code

### ISSUE THREAD

**Issue by dungqut** [tech-srl/code2vec#59]
Hello @urialon  happy new year

I am trying to use your code to adapt with new problem I mean I try to detect vulnerability detection in C/C++

To do that I have replace name of function with name of vulnerability as follows:

    if 'CWE-119' in file_path:

        f.write('CWE119')
    elif 'CWE-399' in file_path:

        f.write('CWE119')

I have successfully created data as input to code2vec, but when running for training I faced some problems, it seems that there is problems with the lables

Could you give any solutions for this?

I really appreciate your help

We may write a transaction paper together if you are interested in to

**Comment by urialon** [comment]
Hi @dungqut ,
Sorry for the late reply.

In order to help I'll need to: know what exactly did you run (the exact command line), how does your new data looks like (can you attack a line or two?), and what errors are you getting.

Best,
Uri

**Comment by dungqut** [comment]
Hello @urialon I really appreciate your reply, I have solved the problem, but definitely I really wish to discuss with you about this 

I can capture some line of code or pictures, but it is much more convenience if you can share your skype, could we can set up a skpye to have quick chat?

I look forward to hearing from you

Regards
Dzung

**Comment by urialon** [comment]
I'm really sorry, but I am maintaining these repositories mostly by myself, and I answer multiple questions and emails every day. 
I don't have time to talk on Skype as I need to focus on my PhD. I hope you understand.
Please describe your questions here and I'll try to help.

**Comment by dungqut** [comment]
Hello @urialon Sure

I can post question on here very soon, I hope we can have some collaboration

I really appreciate your help
