### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by impredicative** [tech-srl/code2vec#6]
Is it possible to provide this for other languages too, e.g. Python, JavaScript, etc.?

**Comment by urialon** [comment]
It is possible and simple to extend this to other languages, see:
https://github.com/tech-srl/code2vec#extending-to-other-languages

However, it requires writing an additional Extractor (similar to the current JavaExtractor) that would take raw Python/JavaScript files and transform them to paths that can be fed to the neural network.

At the moment, I am not planning to extend it, but I would love to adopt contributions,

**Comment by urialon** [comment]
Hi, if it helps, I added a C# extractor.
Best,
Uri

**Comment by mikhfilippov** [comment]
Hi Uri, two questions about supporting other languages:
1. to support say Python one should not just write an extractor, but also train a model on Python files, right?
2. why don't you use code parsers to produce ASTs (e.g. Antlr)?

**Comment by urialon** [comment]
Hi,

1. Right.
2. We didn't use Antlr, but @vovak built a nice library based on Antlr to generate AST paths in any language for our models, and based their format on ours: 
https://github.com/vovak/astminer

Best,
Uri

**Comment by mikhfilippov** [comment]
Awesome, thanks!
