### ISSUE TITLE
Exporting Code Vectors for Oher languages

### ISSUE THREAD

**Issue by shubhamrsangle** [tech-srl/code2vec#62]
Is it possible to export code vectors for any other language than Java? 
As I went through code for interactive prediction, It's written only for Java, So we have to write our different functionalities for other languages or you have any of those?

If you have then 
Can you help me with command for exporting code vectors of particular file if file name is filename.cpp ?

As this is mentioned in Readme that 
If used with the --test <TEST_FILE> flag, a file named <TEST_FILE>.vectors will be saved in the same directory as <TEST_FILE>. Each row in the saved file is the code vector of the code snipped in the corresponding row in <TEST_FILE>.

Now, I trained model for cpp  so <TEST_FILE> can be any cpp file right? or by default it's also taking java file?  

when I run this command

`python3 code2vec.py --load models/cpp/saved_model.release --export_code_vectors --test AMNOI.cpp`

I am getting error 

Traceback (most recent call last):
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 201 fields but have 2 in record
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code2vec.py", line 31, in <module>
    eval_results = model.evaluate()
  File "/home/shubham/Desktop/Windows/BTP/code2vec-master/tensorflow_model.py", line 159, in evaluate
    self.eval_original_names_op, self.eval_code_vectors],
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 201 fields but have 2 in record
	 [[node IteratorGetNext (defined at /home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]

Original stack trace for 'IteratorGetNext':
  File "code2vec.py", line 31, in <module>
    eval_results = model.evaluate()
  File "/home/shubham/Desktop/Windows/BTP/code2vec-master/tensorflow_model.py", line 122, in evaluate
    input_tensors = input_iterator.get_next()
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2500, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3360, in create_op
    attrs, op_def, compute_device)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "/home/shubham/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1751, in __init__
    self._traceback = tf_stack.extract_stack()

and when I am running this command

`python3 code2vec.py --load models/cpp/saved_model.release --export_code_vectors --predict`

It's by default opening input.java but I trained model for CPP

_Originally posted by @shubhamrsangle in https://github.com/tech-srl/code2vec/issues/61#issuecomment-574052594_

**Comment by shubhamrsangle** [comment]
tensorflow.python.framework.errors_impl.InvalidArgumentError: [_Derived_]{{function_node __inference_process_input_row_490_specialized_for_StatefulPartitionedCall_at_tf_graph}} {{function_node __inference_process_input_row_490_specialized_for_StatefulPartitionedCall_at_tf_graph}} Expect 201 fields but have 1195 in record 0

I think you can help me with this.
What are 201 fields here? Is it always necessity that extractor result will be having 201 fields?

**Comment by shubhamrsangle** [comment]
For smaller lines in predict line when I am padding spaces to make 201 fields, I am getting correct output but when some code have greater fields than 201 what should I do ?

**Comment by urialon** [comment]
Hi @shubhamrsangle ,
I'll try to answer all questions, I hope I didn't miss anything.

1. The function of exporting the code vectors is language agnostic. The model exports the code vectors for the language it was trained on. The network does not "know" which language it was trained on.

2. <TEST_FILE> in this case is not a *.cpp file, but a **file that was preprocessed using the preprocessing pipeline** (`preprocess.sh` or its equivalent C#/c++).

3. in `--predict` mode, the code is read from the file `Input.java`, fed to the JavaExtractor than turns it into paths, and then fed into the network. The extractor needs to be replaced in order to transform a cpp file into the paths format. I recommend debugging and see what this line does for Java input: [https://github.com/tech-srl/code2vec/blob/master/interactive_predict.py#L39](https://github.com/tech-srl/code2vec/blob/master/interactive_predict.py#L39)  and then try to implement a similar extractor for C++.

4. The JavaExtractor outputs all paths that are found in a single example. The `preprocess.py` file truncates or pads if necessary. When we have more than 200 paths we randomly sample them. If 200 paths are not enough, this value can be increased here: [https://github.com/tech-srl/code2vec/blob/master/preprocess.sh#L25](https://github.com/tech-srl/code2vec/blob/master/preprocess.sh#L25) for a new dataset and here: [https://github.com/tech-srl/code2vec/blob/master/config.py#L60](https://github.com/tech-srl/code2vec/blob/master/config.py#L60) for the model's side.

I hope it helps.
Uri

**Comment by shubhamrsangle** [comment]
> 2\. TEST_FILE> in this case is not a *.cpp file, but a **file that was preprocessed using the preprocessing pipeline** (`preprocess.sh` or its equivalent C#/c++

What do you mean by this? File which is passed to preprocess.py or preprocess.sh? Because input of preprocess.sh in your code is repository of java files only, where as input of preprocess.py is language independent.
So do you mean that we need to pass that path_context file (input file for preprocess.py)?

**Comment by urialon** [comment]
`preprocess.sh` has two steps: first, transforms raw source code files into space-separated CSV-like files. Second, it calls the `preprocess.py` file which truncates and pads these CSV-like files. 
When extending to a new language, you need to replace only the first part (which transforms raw C++/Java files into the CSV format), and keep the second part.

But - before rushing to export code vectors, did you manage to **train** a C++ model? 
You can't export anything before you have a trained C++ model.

See my previous answer here:
https://github.com/tech-srl/code2vec/issues/60#issuecomment-573389314

**Comment by shubhamrsangle** [comment]
> But - before rushing to export code vectors, did you manage to **train** a C++ model?

Yes, I was able to train model successfully, even saving t2v and all those functionalities worked. All the functionalities other than exporting code vectors was done successfully. 

Can you just please tell that TEST_FILE parameter expect code file or csv like file we got from first part of preprocess.sh ?

**Comment by shubhamrsangle** [comment]
If I use csv like file obtained from first part of preprocess.sh, I get this error saying 201 fields expected but got only 22, I didn't do anything other than frroreeding that csv file to it.

Error msg:

File "/home/shubham/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 201 fields but have 22 in record
	 [[node IteratorGetNext (defined at /home/shubham/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]

Do, I need to edit my csv like file before passing it to --test parameter?

**Comment by urialon** [comment]
Hi @shubhamrsangle ,
For exporting code vectors, as I wrote [in #2 here](https://github.com/tech-srl/code2vec/issues/62#issuecomment-574846525) <TEST_FILE> is a CSV file like we got from the **second** part of `preprocess.sh`.

This file does not need to be edited, just passed through the same preprocessing pipeline as the standard training and test files.

**Comment by shubhamrsangle** [comment]
> This file does not need to be edited, just passed through the same preprocessing pipeline as the standard training and test files.

If I use csv like file obtained from first part of preprocess.sh, I get this error saying 201 fields expected but got only 22, I didn't do anything other thanpassing that csv file to it.

Error msg:

File "/home/shubham/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 201 fields but have 22 in record
[[node IteratorGetNext (defined at /home/shubham/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]

**Comment by urialon** [comment]
> a CSV file like we got from the **second** part of `preprocess.sh`.

This is why I wrote **second** part.
