### ISSUE TITLE
preprocessing problem about method names

### ISSUE THREAD

**Issue by rrrxderek** [tech-srl/code2vec#68]
Hi, I am confused about preprocessing my own data and I need your help.
In preprocess.sh it says that TRAIN_DIR, VAL_DIR and TEST_DIR should be paths to directories containing sub-directories with .java files each of {TRAIN_DIR, VAL_DIR and TEST_DIR} should have sub-dirs, and data will be extracted from .java files found in those sub-dirs).
So my own understanding is that the names of those sub-dirs under  {TRAIN_DIR, VAL_DIR and TEST_DIR} are the methods of the java files found in those sub-dirs. But after I preprocessed the data and trained the model then test, the log showed something weird. For example: Original: main, predicted 1st: main
But there is no method name 'main'  in my data.
Can you help me figure it out?

**Comment by urialon** [comment]
Hi @rrrxderek ,
The names of those sub-dirs under {TRAIN_DIR, VAL_DIR and TEST_DIR} are just names of *repositories* that the Java files came from, and have no significance. 

Regarding the name "main" - I suggest that you check again if there's "main" or "Main", and verify that in the `preprocess.sh` script you pointed to the right directories.

Best,
Uri

**Comment by rrrxderek** [comment]
Hi Uri,
Thank you for the reply. So what should I do if I want to add java files with new functions and new method names for training?  Should I just name the java files with their method name?

Best,
Derek

**Comment by urialon** [comment]
Just put them in the appropriate subdirectories. Neither the names of the files nor the names of the directories don't matter. You can also have files that have multiple methods in them.

You can download a raw (un-preprocessed) dataset and take a look at its structure, such as Java-small or Java-med. See:
https://github.com/tech-srl/code2seq/blob/master/README.md#java

Best,
Uri

**Comment by rrrxderek** [comment]
Problem solved, thank you!
