### ISSUE TITLE
More vectors exported and preprocess data than instances passed

### ISSUE THREAD

**Issue by Gueloi** [tech-srl/code2vec#69]
Hello. I used code2vec to preprocess some dataset. However, the number of instances generated after preprocess is different from the instances passed as input (almost double). What could be the problem?

**Comment by urialon** [comment]
Hi,
What exactly do you refer to bythe input instances? Did you count files or methods?

**Comment by Gueloi** [comment]
I mean .java files. I counted files. I am trying to use to do some kind of transfer learning

**Comment by urialon** [comment]
Hi,
Preprocessing creates an example per method, so it is very likely that one Java file will produce two examples.

**Comment by Gueloi** [comment]
Thank you, so won't be possible to use for my work. I needed per file, so i can use to another type of classification task. Thank you for your time!!
