### ISSUE TITLE
Issue Converting from astminer

### ISSUE THREAD

**Issue by kyledampier** [tech-srl/code2vec#72]
Issue Converting from [astminer](https://github.com/JetBrains-Research/astminer/tree/master-dev/astminer-cli).
-----
The format I am receiving from astminer is not the same as the`.c2v` format I am receiving 4 files

**Files from output**
* `path_contexts_0.csv`
    * output seperated by`|`
    * comma separated triples
* `node_types.csv`
    * id, node_type
* `paths.csv`
    * id, path
* `tokens.csv`
    * id, token

-----

I noticed you referenced this project for adding new languages. I cannot figure out how to change the four-file csv format to the `.c2v` format. Any help is appreciated. I tried using your preprocessing.sh script however it seems to only work with new `.java` files. And was wondering what I need to do in order to convert to the `.c2v` the format in order to start training for different languages.

Thank you,
Kyle Dampier

**Comment by urialon** [comment]
Hi Kyle,
Thank you for your interest in code2vec!

In general - I don't know. 

But did you check out their code2vec section?
https://github.com/JetBrains-Research/astminer/blob/master-dev/astminer-cli/README.md#code2vec

**Comment by SimoneBrigante** [comment]
Hi @kyledampier,
I had your same problem at the beginning.
If I have understood correctly the astminer extractor does the work of the first part of the `preprocessing.sh` (between line 41 and 49).
So the `path_contexts_0.csv` files are equivalent to the `.raw.txt` files that those lines would generate.
I hope I have been clear enough

Simone
