### ISSUE TITLE
Downloadable histogram files

### ISSUE THREAD

**Issue by BrynMarieR** [tech-srl/code2vec#74]
Hello,

First, thanks for the great resource!

I am trying to evaluate the code2vec pre-trained models on new test-data that is just small perturbations on the java-small codebase. Using the posted code with some minor modifications, it is possible to pre-process new batches of test files (.java files) by utilising JUST the histogram files, rather than needing to re-run all of the training samples in java-small first. However, unfortunately, all the histogram files are automatically removed at the end of a pre-processing session.

In the end, for me this meant pre-processing all the many training files of java-small again (once), saving the histogram files and deleting the training data and then pre-processing my new test sets. 

Would it be possible to have the histogram files made available along with the rest of the pre-trained data? It would be great for e.g. java-large.

Thanks,
Bryn

**Comment by urialon** [comment]
Hi Bryn,
Thank you for your interest in code2vec!

As part of the preprocessing, the histograms are indeed deleted. However, their information is hidden inside the `*.dict.c2v` file:
https://github.com/tech-srl/code2vec/blob/master/preprocess.py#L12

So if you take our `*.dict.c2v` file and un-pickle it in the same order, you'll get the same information. Then you can use these un-pickled dictionaries to preprocess new test sets here: https://github.com/tech-srl/code2vec/blob/master/preprocess.py#L133 .

Does that help?

Best,
Uri

P.S. 1 - our newer [code2seq](https://code2seq.org/) model is stronger than code2vec
P.S. 2 - if it's relevant, we were also curious about the effect of perturbed examples on a trained model. This lead to this adversarial examples paper: https://arxiv.org/pdf/1910.07517

**Comment by BrynMarieR** [comment]
Hi Uri,

Thanks for the quick follow-up! That's good to know, cheers. And thanks for the link to code2seq and your adversarial examples paper -- I'm actually doing a bit of a follow-up to the latter, which is why I'm using code2vec. 

Best wishes,
Bryn
