### ISSUE TITLE
Using --export_code_vectors

### ISSUE THREAD

**Issue by crimsonfan** [tech-srl/code2vec#76]
Hi,
First of all, I would like to thank you for all your works. I'm currently a student and I'm eager to learn more about this project.
So i met an issue that: 
- The feartures said that 
![image](https://user-images.githubusercontent.com/52530504/81463402-9e708780-91e3-11ea-9c0a-60184649bc5e.png)
So I tried with 
![image](https://user-images.githubusercontent.com/52530504/81463421-c19b3700-91e3-11ea-963f-bae9902da0c2.png)
And I received 
![image](https://user-images.githubusercontent.com/52530504/81463456-ff985b00-91e3-11ea-8e69-d93d966b5f2e.png)
But I haven't found any generated file in the folder.
I would like to ask that if I need some more parameter or where the project stores that generated file of vector.

Thanks.

**Comment by crimsonfan** [comment]
Sorry, I found solutions, I was careless when reading  tutorial.

**Comment by urialon** [comment]
Great, I'm glad to hear that you find a solution!
