### ISSUE TITLE
[Model Hyper Parameters Issue]

### ISSUE THREAD

**Issue by vinayak618** [tech-srl/code2vec#78]
Hi @urialon,

Thank you so much for the wonderful research, for sure it will be used in wide variety of research across domains.

Is there any README file or any documents to adjust model hyper parameters according to the hardware(GPU) available. I'm using GTX 1070 8GiB machine and by using the default parameters, the memory allocation is overflowing and running into error. Is there any work around?
It would be great help.

Thanks

**Comment by urialon** [comment]
Hi @vinayak618 ,
Thank you for your interest in code2vec and for your kind words.

There is no official documentation, but you can decrease batch size by half, it will most probably be ok.

Best,
Uri

**Comment by vinayak618** [comment]
Hi @urialon ,

Already tried couple of options, including reducing Batch Size.
Still facing same allocation issues. Any alternate solution?

Regards,
Vinayak N Baddi

**Comment by vinayak618** [comment]
Hi @urialon,

I tried reducing the batch size, but see no improvement.
Here is the allocation tensor which is causing the error

> OP_REQUIRES failed at resource_variable_ops.cc:415 : Resource exhausted: OOM when allocating tensor with shape[807138,128] 

Any other solution to solve the issue?

Regards,
Vinayak N Baddi

**Comment by urialon** [comment]
In general, any other parameter can be decreased to save GPU space. 
Maybe decreasing `EMBEDDINGS_SIZE` by half will be effective.

**Comment by vinayak618** [comment]
Hi @urialon ,
Thanks, reducing EMBEDDINGS_SIZE, helped.
Any idea, how we can extend it to own dataset like C++?

**Comment by urialon** [comment]
Sure, see: https://github.com/tech-srl/code2vec/blob/master/README.md#extending-to-other-languages

**Comment by vinayak618** [comment]
Hi @urialon ,

Thank you so much for quick responses.
Please take care.

Thanks and Regards,
Vinayak N Baddi
