### ISSUE TITLE
Need help with using the pre-trained model to get vector of an out of vocabulary method name

### ISSUE THREAD

**Issue by ngocpq** [tech-srl/code2vec#8]
Hi, 
I would like to use the pre-trained model to find the most similar name of a given word, as similar to the "Most similar feature" in the website https://code2vec.org .

However, when I input a method name that is out of the method name vocabulary (I guest that), for example "bitcounts", I got the error "word 'bitcounts' not in vocabulary".

Could you show me how to over-come this issue.

My code is as bellow:
```python
from gensim.models import KeyedVectors as word2vec

vectors_text_path = 'C:/workplace/code2vec/models/java14_model/targets.txt'
model = word2vec.load_word2vec_format(vectors_text_path, binary=False)

print("input method name: ")
method_name = input()

print("most similar: ")
rs = model.wv.similar_by_word(method_name)
print(rs)
```

Thank you in advance

**Comment by urialon** [comment]
Hi,
The target name vectors contain about 300k names and their vectors, but since the number of possible names is infinite - there are names that are not in the vocabulary.

In general, you can check if a word is in the vocabulary using:
```
if method_name in model.wv.vocab:
  rs = model.wv.similar_by_word(method_name)
  print(rs)
else:
  # Print an error, 
  # or use an approximation heuristic like: finding words that method_name is included in, 
  # finding words that are included in method_name, remove trailing "s" etc.
```
In this specific case, you can approximate the similarity by looking for `bitcount` (which does exist) instead of `bitcounts`.
But in general, dealing with out-of-vocabulary in pretrained word embeddings is a difficult question that is part of active research in NLP.

**Comment by ngocpq** [comment]
Hi @urialon , thank you for your response quickly,

Could you suggest me a trick, or a walk around method such that we can output a approximate list of similar words (as I see in the demonstration website  https://code2vec.org), instead of an error or return nothing for the case of Out-of-vocabulary?

I have just re-run the Most similar demonstration in the demonstration website, and I guest that it deal with this case as follows:
(1) splitting a long method name into several sub-words, which occurred in the vocabulary, 
(2) and then, combine (in some how) the vectors of these sub-words to produce one vector
(3) considering the combined vector as the embedding of the long method name.

Am I right? 
If so, could you please tell me how the demonstration website did, or suggest me a good way to combine the vectors of the sub-words to approximate the vector of the method name?

I would really appreciate your help.

**Comment by ngocpq** [comment]
I got it. 
Thank you very much for your help, Uri Alon.

**Comment by Shushank96** [comment]
Hello there..
I need a suggestion to use this pretrained model for generating vector for a specific input of java code (vector only as output)
