### ISSUE TITLE
Get code vector instead of prediction

### ISSUE THREAD

**Issue by lyqssb** [tech-srl/code2vec#80]
How can i let the code2vec.py just output the code vector rather than prediction, or just let it stop on the stage of code vector?

**Comment by urialon** [comment]
Hi,
See:
https://github.com/tech-srl/code2vec#exporting-the-code-vectors-for-the-given-code-examples

**Comment by lyqssb** [comment]
wow,sorry i overlook it. Thank you very much! @urialon
