### ISSUE TITLE
no problem

### ISSUE THREAD

**Issue by hellokitty753159** [tech-srl/code2vec#83]

**Comment by urialon** [comment]
Hi @hellokitty753159,
Can you please provide more details:

1. How is the readme different than the code?
2. What problem are you encountering in exporting code vectors?
3. Do all other options work? For example, the manual examination of a
trained model ("--predict mode")?
4. What are your operating system, python version, and tensorflow version?

**Comment by hellokitty753159** [comment]
> encountering

I have solved the problem. Thanks for your reply. Very good paper.

**Comment by urialon** [comment]
Great, glad to hear :-)
