### ISSUE TITLE
Differences between the pre-trained models

### ISSUE THREAD

**Issue by Kadakol** [tech-srl/code2vec#93]
Hi @urialon ,

I was trying out the pre-trained models [1](https://github.com/tech-srl/code2vec#downloading-a-trained-model-14-gb), [2](https://github.com/tech-srl/code2vec#downloading-a-trained-model-35-gb-which-can-be-further-trained) and I came across some differences in the output of both the models.

Basically what I tried to do is to use the --predict flags with the provided models. Following are the results that I got with the default Input.java file (factorial code)

### models/java14_model/saved_model_iter8.release:

> Original name:  f
>         (0.472304) predicted: ['m']
>         (0.174315) predicted: ['fact']
>         (0.101179) predicted: ['factorial']
>         (0.095780) predicted: ['faculty']
>         (0.067391) predicted: ['get', 'n']
>         (0.038753) predicted: ['get', 'result', 'score']
>         (0.013598) predicted: ['is', 'power', 'of']
>         (0.013113) predicted: ['digit', 'count']
>         (0.012808) predicted: ['comb']
>         (0.010760) predicted: ['get', 'in']
> Attention:
> 0.258571        context: n,(NameExpr0)^(BinaryExpr:times)_(MethodCallExpr1)_(BinaryExpr:minus)_(NameExpr0),n
> 0.159237        context: 1,(IntegerLiteralExpr1)^(BinaryExpr:minus1)^(MethodCallExpr)_(NameExpr2),f
> 0.102514        context: int,(PrimitiveType0)^(MethodDeclaration)_(NameExpr1),METHOD_NAME
> 0.082340        context: 0,(IntegerLiteralExpr1)^(BinaryExpr:equals)^(IfStmt)_(BlockStmt)_(ReturnStmt)_(IntegerLiteralExpr0),1
> 0.060176        context: METHOD_NAME,(NameExpr1)^(MethodDeclaration)_(BlockStmt)_(IfStmt)_(BlockStmt)_(ReturnStmt)_(BinaryExpr:times)_(NameExpr0),n
> 0.059877        context: int,(PrimitiveType1)^(Parameter)^(MethodDeclaration)_(BlockStmt)_(IfStmt)_(BlockStmt)_(ReturnStmt)_(IntegerLiteralExpr0),1
> 0.042954        context: int,(PrimitiveType0)^(MethodDeclaration)_(Parameter)_(VariableDeclaratorId0),n
> 0.041031        context: n,(VariableDeclaratorId0)^(Parameter)^(MethodDeclaration)_(BlockStmt)_(IfStmt)_(BlockStmt)_(ReturnStmt)_(BinaryExpr:times)_(NameExpr0),n
> 0.033209        context: int,(PrimitiveType0)^(MethodDeclaration)_(Parameter)_(PrimitiveType1),int
> 0.029109        context: n,(VariableDeclaratorId0)^(Parameter)_(PrimitiveType1),int

### models/java14m_trainable/saved_model_iter8:

> Original name:  f
>         (0.294019) predicted: ['count', 'ones']
>         (0.226618) predicted: ['digit', 'count']
>         (0.106020) predicted: ['get', 'result', 'score']
>         (0.084841) predicted: ['get', 'num', 'cols']
>         (0.065597) predicted: ['m']
>         (0.056080) predicted: ['ceil']
>         (0.047290) predicted: ['even']
>         (0.045189) predicted: ['next', 'power', 'of', 'two']
>         (0.043904) predicted: ['fact']
>         (0.030444) predicted: ['skip', 'bytes']
> Attention:
> 0.186223        context: n,(NameExpr0)^(BinaryExpr:times)_(MethodCallExpr1)_(BinaryExpr:minus)_(NameExpr0),n
> 0.137359        context: int,(PrimitiveType0)^(MethodDeclaration)_(NameExpr1),METHOD_NAME
> 0.129210        context: METHOD_NAME,(NameExpr1)^(MethodDeclaration)_(BlockStmt)_(IfStmt)_(BlockStmt)_(ReturnStmt)_(BinaryExpr:times)_(NameExpr0),n
> 0.090641        context: 1,(IntegerLiteralExpr1)^(BinaryExpr:minus1)^(MethodCallExpr)_(NameExpr2),f
> 0.074537        context: 0,(IntegerLiteralExpr1)^(BinaryExpr:equals)^(IfStmt)_(BlockStmt)_(ReturnStmt)_(IntegerLiteralExpr0),1
> 0.071756        context: n,(VariableDeclaratorId0)^(Parameter)^(MethodDeclaration)_(BlockStmt)_(IfStmt)_(BlockStmt)_(ReturnStmt)_(BinaryExpr:times)_(NameExpr0),n
> 0.070238        context: int,(PrimitiveType0)^(MethodDeclaration)_(Parameter)_(PrimitiveType1),int
> 0.055065        context: int,(PrimitiveType0)^(MethodDeclaration)_(Parameter)_(VariableDeclaratorId0),n
> 0.053321        context: n,(NameExpr0)^(BinaryExpr:equals)^(IfStmt)_(BlockStmt)_(ReturnStmt)_(IntegerLiteralExpr0),1
> 0.018855        context: n,(VariableDeclaratorId0)^(Parameter)^(MethodDeclaration)_(BlockStmt)_(IfStmt)_(BlockStmt)_(ReturnStmt)_(IntegerLiteralExpr0),1

I am curious to know how the results from both these models are so different. I had assumed they were basically the same model, one in trainable state and the other in released state. Could you please help me understand?

My aim is try and export code vectors for some of my own sample java code using the pre-trained models. Is there any reason why I should prefer to use one over the other, i.e., the trainable model vs the released model? Or does it not matter much as long as I pick one of these and stick to it?

**Comment by urialon** [comment]
Hi @Kadakol ,

Sorry for the confusion - these are not the same model.
The first one is the model that serves the website ([www.code2vec.org](www.code2vec.org)) . 
The second model was trained afterward. 

They are equivalent in terms of accuracy, but they might return different predictions for specific queries. 
It doesn't matter which model you choose, as long as you stick to the same one. You can try to see if there's one of them that works better for you. The **non**-trainable one might work slightly faster and take less memory.

Best,
Uri

**Comment by Kadakol** [comment]
Hi @urialon ,

Thank you for your quick response!

> Sorry for the confusion - these are not the same model.
> The first one is the model that serves the website ([www.code2vec.org](www.code2vec.org)) .
> The second model was trained afterward.
> 
> They are equivalent in terms of accuracy, but they might return different predictions for specific queries.

I see what you mean.

> It doesn't matter which model you choose, as long as you stick to the same one. You can try to see if there's one of them that works better for you. The **non**-trainable one might work slightly faster and take less memory.

OK. Let me start off with the non-trainable model then.

Thank you for clarifying :)

Regards,
Akshay.
